<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Monolith</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Entities\Orders\Orders.csproj" />
    <ProjectReference Include="..\..\Entities\Customers\Customers.csproj" />
  </ItemGroup>

</Project>
