<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <UserSecretsId>eff1a54d-e91d-4bb7-8c4a-ab7fdd8f1ebc</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\Calculator.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>
